### ISSUE TITLE
Suppress IFDIFF warnings by introducing a debug mode

### ISSUE THREAD

**Issue by Schlevidon** [andreassommer/ifdiff#8]
## Summary
At the moment IFDIFF may produce a lot of warnings that are irrelevant to end users and are only meant for developers. We should add an option to suppress these unnecessary warning.
## Example
An example that will produce a lot of warnings, presumably when extending a solution to a switching point with very small step sizes.
### ODE system
    % Exercise 2 System
  
    function dx = ex2RHS(t,x,p)
        dx = zeros(2,1);
        q1 = (50/27)*t^2 -(100/3)*t + 400/3;
        q2 = (1000 - x(2))*(p(1)*(t-19) + p(2));
        if x(1)<= 750
            dx(1) = q1;
        else
            dx(1) = q1 - q2;
        end
        if x(1) > 750
            if x(1) <= 800
                dx(2) = -300;
            end
        end
    end
### Solver Code
Note that the `plotSensitivities` and `plotSensitivitiesSwitched` functions are only available in the `workshop` branch.

    % Solution
    integrator = @ode45;
    options = odeset('Abstol', 1e-8, 'Reltol', 1e-6);
    
    p = [3/4,1/4];
    tEnd = 30;
    tSpan = [0 tEnd];
    x0 = [0; 1000];
    
    datahandle = prepareDatahandleForIntegration('ex2RHS','integrator',integrator, 'options', options);
    sol = solveODE(datahandle, tSpan,x0,p);
    
    rhs = @(t,x)ex2RHS(t,x,p);
    % sol = integrator(rhs, tSpan, x0, options)
    
    T = 0:0.1:tEnd;
    X = deval(sol, T);
    plot(T, X(1,:), 'r', T, X(2,:), 'g');
    
    
    %plotSensitivities(sol,@ex2RHS,p,integrator, options);
    plotSensitivitiesSwitched(datahandle, sol,p);

## Proposed Solutions
- Add a debug mode (e.g. by introducing a boolean flag in the config). Warnings like in the above example can then be omitted when the debug mode is disabled. 🥇
- Adding a logging system was rejected for the following reasons: ❌ 
  - Introducing a logging system may increase the complexity of the project.
  - Logs may become too cluttered with irrelevant information, ultimately rendering them useless.
  - The first proposal gives developers more control and flexibility when debugging (e.g. being able to not only output messages, but also adjust the behavior of IFDIFF).

**Comment by andreassommer** [comment]
Add warning identifier to the warnings, so they can be silenced explicitly:
warning('IFDIFF:MALFORMED_IF', 'Found invalid IF condition in source file %s at line %d', sourcefile, filenumber);

Those warning can be silenced via
warning('off', 'IFDIFF:MALFORMED_IF') turns off that specific warning

The debug-mode should rather not silence warnings, but suppress info and status messages.
